### ISSUE TITLE
Kura5 streams trigger repeated notifications

### ISSUE THREAD

**Issue by shenef** [Prof9/livenow#5]
When a Kura5 stream is live, it triggers a new notification for that stream every few minutes.

**Comment by Prof9** [comment]
The problem is that because this game is in two queues (Twitch and TwitchUser) for the same platform, the stream decays faster than it can be refreshed by API calls (because the TwitchUser queue is small, the game is refreshed more frequently in that queue than in the normal Twitch queue).

As a workaround I've made the platform check for stream decay a bit more strict (previously it was a substring comparison). This relies on the fact that a TwitchUser game is also in a Twitch queue, otherwise it will never decay. This was not always the case, but it is the case now, so for now this should be good enough.

Since Live Now relies on the Legacy Twitch API v5 which will be shutdown at the end of February 2022, I don't really think it's worth looking more into a long-term solution since Live Now would probably need to be rebuilt to take advantage of the new API anyway.
